import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

    <body className={inter.className}>
    <div className='main-nav'>
      <h1>Find Your Next Trick</h1>
      <p>The Ultimate Collection of Dog Tricks!</p>
    </div>
    {children}
    </body>


    </html>
  );
}
